// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0KYOfwcN2blY2nGrQO7No860EBHhhzpg',
    appId: '1:354671670812:web:9fffc1dfa6df40472151d9',
    messagingSenderId: '354671670812',
    projectId: 'temple-procession-walter',
    authDomain: 'temple-procession-walter.firebaseapp.com',
    storageBucket: 'temple-procession-walter.firebasestorage.app',
    measurementId: 'G-X6M6MX9P8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSb5okBesPtGf5g_TroIO5QD5EFLW10uY',
    appId: '1:354671670812:android:cf0e37351af74dda2151d9',
    messagingSenderId: '354671670812',
    projectId: 'temple-procession-walter',
    storageBucket: 'temple-procession-walter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDklAAPeMcs6m9x3q88nibhxBDfA2iUWhE',
    appId: '1:354671670812:ios:48d99f3657f974a12151d9',
    messagingSenderId: '354671670812',
    projectId: 'temple-procession-walter',
    storageBucket: 'temple-procession-walter.firebasestorage.app',
    iosBundleId: 'com.walter.templeprocessiontracker',
  );
}
